feat: Batch Mode API / Headless
anthropics/claude-quickstarts pull request #139
Opened 2024-10-30 00:01 UTC by dkindlund

This PR adds a new mode called "Batch Mode" to the `computer-use-demo` container.  If you specify `RUN_MODE=batch` as an additional environment variable, the code will turn *off* Streamlit (on port 8080) and turn *on* the Batch Mode API (on port 8000).

This will allow users to submit asynchronous tasks via this endpoint:

```bash
curl -X POST http://localhost:8000/tasks \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "Open the Firefox browser and navigate to google.com"
  }'
```

If the container is NOT running in Google Cloud Run, then this task will return immediately with a task_id.  You can then fetch the status and results of the task through the `/tasks` endpoint, accordingly.

If the container IS running in Google Cloud Run, then this task will switch to synchronous processing.  Only when the Agent fully completes, will the final results be returned to the client.

See the updated `README.md` for more details on these modes (and caveats).

2024-10-30 21:02 UTC, x5a requested changes
thanks for the contribution @dkindlund.

I'm glad you found this project useful. In its current state, this PR doesn't meet a few criteria we're looking for new features:
* provider/environment agnostic: this only works with cloud run; the "local" behavior is substantively different than cloud run.
* broad applicability: because the batch mode resets between inputs, you can't take multi-turn actions. as such, the utility is fairly limited for multi-turn agent use.

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/Dockerfile
> +    python -m pip install fastapi uvicorn
this should be covered by the subsequent line, correct?

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/requirements.txt
> +uvicorn[standard]>=0.24.0
add starlette/pydantic given that they are now explicit imports

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/batch_api.py
> +    messages: list = []
```suggestion
    messages: list[BetaMessage] = []
```

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/batch_api.py
> +    provider: APIProvider = APIProvider.VERTEX  # Default to VERTEX since we're in Vertex environment
not necessarily true for a general use case.

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/batch_api.py
> +IS_CLOUD_RUN = os.getenv('K_SERVICE') is not None  # Cloud Run sets this automatically
this would maybe better be called `IS_STATELESS` or something more generic to indicate that it's behind a load balancer.

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/batch_api.py
> +                    "pkill -f 'gedit' || true",
claude can start arbitrary programs, so this is not sufficient. also see https://github.com/anthropics/anthropic-quickstarts/blob/main/computer-use-demo/computer_use_demo/streamlit.py#L152

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/batch_api.py
> +        return self.model
use `model: str = field(default_factory=_get_model)` instead to simplify

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/image/entrypoint.sh
> +if [ "$RUN_MODE" = "batch" ]; then
from my perspective, batch mode and streamlit aren't necessarily mutually exclusive (although if both are supported simulatenously, there should probably be a shared lock)

2024-10-30 21:02 UTC, x5a commented on computer-use-demo/computer_use_demo/batch_api.py
> +    if IS_CLOUD_RUN:
I understand why, but if I wasn't familiar with cloud run, I'd find it surprising how different the cloud run implementation is from the local implementation.

2024-11-22 23:44 UTC, x5a commented
@dkindlund since I haven't heard back, I'm going to close this out.

2024-11-22 23:44 UTC, closed without merging

2024-11-23 19:55 UTC, dkindlund commented
Hey @x5a , thanks for the feedback.  It will probably take me a couple of months to get through the updates to this PR.  When I'm ready, should I reopen this PR or submit a new one?

2024-11-23 20:04 UTC, dkindlund commented
> provider/environment agnostic: this only works with cloud run; the "local" behavior is substantively different than cloud run.

Correct. I did check other IaaS platforms, such as:
* AWS App Runner: Unfortunately, they only allow max execution times [of up to 2 minutes](https://github.com/aws/apprunner-roadmap/issues/104) (which severely reduces the efficacy of the service overall).  In contrast, Google Cloud Run supports execution times of up to 60 minutes.
* I didn't provide code for an equivalent Azure service, mainly because that was out of scope of this PR.

@x5a , so I'm trying to understand something here... will you *not* be able to accept this PR *unless* the PR covers every possible IaaS provider (because it needs to be environment "agnostic")?  Or is there a minimum set you need support for, first?

Please let me know the answer to this before I commit additional cycles on refinements here -- just trying to understand the acceptance criteria.

2024-11-23 20:06 UTC, dkindlund commented on computer-use-demo/computer_use_demo/batch_api.py
> +IS_CLOUD_RUN = os.getenv('K_SERVICE') is not None  # Cloud Run sets this automatically
The `K_SERVICE` env variable is absolutely Google Cloud Run specific -- it's not something supported by any other IaaS platform provider, if I recall correctly.  Therefore, using a generic name like `IS_STATELESS` might be a bit misleading (unless we figure out the equivalent mechanism for AWS App Runner and the Azure equivalent).